tunnel: e1ecc9e4-c2ad-4614-9d1b-d5b0191dfb61
credentials-file: /root/.cloudflared/e1ecc9e4-c2ad-4614-9d1b-d5b0191dfb61.json

ingress:
  - hostname: db.bid-end.homeiworks.uk
    service: tcp://localhost:5432
  - service: http_status:404
