name = "bid-search-app"
compatibility_date = "2024-03-20"
main = ".open-next/worker.js"

[[d1_databases]]
binding = "DB"
database_name = "bid-data"
database_id = "ec6cdb10-1c27-442f-a8a2-ada20ef2abd4"
preview_database_id = "ec6cdb10-1c27-442f-a8a2-ada20ef2abd4"
