name = "bid-search-app"
compatibility_date = "2024-09-23"
main = ".open-next/worker.js"
compatibility_flags = ["nodejs_compat"]

[vars]
DB_USER = "user"
DB_DATABASE = "postgres"
DB_HOSTNAME = "db-bids.homeiworks.uk"
DB_PORT = "5432"
